version: "3.3"

services:
  result_pgsql:
    build: ./docker/postgres/
    restart: always
    env_file:
      - docker/config/db.env
    ports:
      - "5432:5432"
    networks:
      - book_network

  result_app:
    build: .
    depends_on:
      - result_pgsql
    restart: always
    env_file:
      - docker/config/app.env
    ports:
      - "8080:8080"
    networks:
      - book_network

networks:
  book_network:
    driver: bridge