spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/result
    username: postgres
    password: result
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
